export enum enAppSession {
    IsFirstTime,
    Ref_User_ID,
    FullName,
    MobileNumber,
    EmailID,
    ProfilePic,
    Ref_Device_GUID,
    HasLogin,
    //Below for Profile Display Page
    AuthorityIDs,
    Bio,
    CreatedBy,
    Gender,
    GovitID,
    Password,
    PayPalEmailID,
    ProfilePhoto,
    Response,
    SocialProfileUrl,
    StudioGears,
    UserCode,
    UserMasterDataIDs,
}